#!/usr/bin/env sh
echo "Packaging Linux..."
echo "Clearing old package..."
rm ../Linux/PolyFold.tgz
echo "Creating root directory..."
mkdir -p ../Linux/PolyFold
echo "Copying target sub-directories..."
cp -r ../PolyFold/target/PolyFold ../Linux/PolyFold
cp -r ../PolyFold/target/classes ../Linux/PolyFold
echo "Updating launcher script..."
rm ../Linux/PolyFold/PolyFold/bin/launcher
cp ./linux_launcher ../Linux/PolyFold/PolyFold/bin/launcher
echo "Creating tar ball..."
tar -czf ../Linux/PolyFold.tgz ../Linux/PolyFold
echo "Cleaning up..."
rm -rf ../Linux/PolyFold
