#!/usr/bin/env sh
echo "Packaging Mac..."
echo "Clearing old package..."
rm ../Mac/PolyFold.tgz
echo "Copying Mac template..."
cp -r ./mac_template.app PolyFold.app
echo "Copying target sub-directories..."
cp -r ../PolyFold/target/PolyFold/* PolyFold.app/Contents
cp -r ../PolyFold/target/classes PolyFold.app
echo "Zipping..."
tar cfz PolyFold.tgz PolyFold.app
mv PolyFold.tgz ../Mac
echo "Cleaning up..."
rm -rf PolyFold.app 
echo "Done"
