#!/usr/bin/env sh
echo "Packaging Mac..."
echo "Clearing old package..."
rm ../Mac/PolyFold.zip
echo "Moving Mac template..."
cp -r ./mac_template.app ../Mac/PolyFold.app
echo "Copying Contents sub-directories..."
cp -r ../PolyFold/target/PolyFold/* ../Mac/PolyFold.app/Contents
echo "Copying classes directory..."
cp -r ../PolyFold/target/classes ../Mac/PolyFold.app
echo "Zipping..."
zip -qr ../Mac/PolyFold.zip ../Mac/PolyFold.app
echo "Cleaning up..."
rm -rf ../Mac/PolyFold.app
echo "Done"
